version: '3.3'

services:
  nexus:
    container_name: nexus
    image: sonatype/nexus3:3.33.0
    ports:
      - "8081:8081"
    volumes:
      - ./init-artifactory/init.sh:/nexus-data/init.sh
      # chown nexus:nexus nexus-data/init.sh 
      # chmod 777 nexus-data/init.sh 
      # ./nexus-data/init.sh 
    
     
    

  # init-artifactory:
  #   container_name: init-artifactory
  #   image: alpine/curl:3.14
  #   volumes:
  #     - "./init-artifactory/init.sh:/var/lib/init.sh"
  #   entrypoint: /bin/sh
  #   command:
  #     - "/var/lib/init.sh"
  #   depends_on:
  #     - "nexus"
  # terragrunt:`
  #   container_name: terraform
  #   image: alpine/terragrunt:1.1.2
  #   volumes: 
  #     - "./terraform-code:/apps"
  #   command: 
  #     - "bash"
  #     - "init-backend.sh"
  #   depends_on:
  #     - "init-artifactory"