version: '3.3'

services:
  nexus:
    container_name: nexus
    image: sonatype/nexus3:3.33.0
    ports:
      - "8081:8081"
  terragrunt:
    container_name: terraform
    image: alpine/terragrunt:1.1.2
    volumes: 
      - "./terraform-code:/apps"
    command: 
      - "bash"
      - "init-backend.sh"


  
